### ISSUE TITLE
[BE] E2E 테스트 환경 설정

### ISSUE THREAD

**Issue by sichoi42** [Pong-Arcade/ft_transcendence#25]
### 작업 설명

E2E 테스트를 위한 기초 환경 설정 작업을 진행하겠습니다.

### 접근 방법

- 테스트 전용 DB 연결을 구성한다.
- 가짜 `FtStrategy`을 만들어, 42 로그인 후 세션을 생성하는 과정 자체를 모킹한다. (실제로 로그인하지 않고도 서버에 세션을 만들고, 클라이언트의 쿠키에 session id 삽입)
- 위 두가지 환경이 갖추어진 테스트용 `AppModule`을 생성한다.
- 테스트용 `AppModule`을 인스턴스화하고, 이를 통해 테스트를 진행한다.

**Comment by youngpar** [comment]
lgtm
